config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get('/', {to: 'home#index', as: 'root'})
  get('/about', {to: 'home#about', as: 'about'})

  get('/contacts/new', {to:'contacts#new', as: 'contacts_new'})
  post('/contacts', {to: 'contacts#create'})
  
  get('/users/panel', {to: 'users#panel', as: 'users_panel'})

  resources :products do
    resources :reviews, shallow: true, only:[:create, :destroy] do
      resources :likes, only:[:create, :destroy]
      resources :votes, only: [:create, :update, :destroy]
    end
    resources :favorites, shallow: true, only:[:create, :destroy]
  end

  resources :favorites, only: [:index]

  resources :users, only:[:new,:create]

  resource :session, only:[:new,:create, :destroy] #singlar not plural

  resources :news_articles

  # Delay_Job
  match(
    "/delayed_job",
    to: DelayedJobWeb,
    anchor:false,
    via:[:get,:post]
  )
end

app/models/product.rb
class Product < ApplicationRecord
    belongs_to :user
    
    has_many :reviews, dependent: :destroy

    has_many :favorites, dependent: :destroy
    has_many :favoriters, through: :favorites, source: :user

    has_many :taggings, dependent: :destroy
    has_many :tags, through: :taggings

    DEFAULT_PRICE = 1

    before_validation :set_default_price
    before_save :capitalize_title

    validates :title, presence: true, uniqueness: true
    validates :price, numericality: { greater_than: 0 }
    validates :description, presence: true, length: { minimum: 2 }

    #Getter
    def tag_names
        self.tags.map(&:name).join(", ")
    end

    #Setter
    def tag_names=(rhs)
        self.tags = rhs.strip.split(/\s*,\s*/).map do |tag_name|
        Tag.find_or_initialize_by(name: tag_name)
        end
    end

    private
    def set_default_price
        self.price ||= DEFAULT_PRICE
    end
    
    def capitalize_title
        self.title.capitalize!
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
    before_action :authenticate_user!, except:[:index, :show]
    before_action :find_product, only: [:show, :edit, :update, :destroy]
    before_action :authorize_user!, only:[:edit,:update,:destroy]

    def index
        if params[:tag]
            @tag = Tag.find_or_initialize_by(name: params[:tag])
            @products = @tag.products.all.order('updated_at DESC')
        else
            @products = Product.all.order(created_at: :desc) 
        end
    end

    def new
        @product = Product.new
    end

    def create
        @product = Product.new product_params
        @product.user = current_user
        if @product.save
            ProductMailer.new_product(@product).deliver_later
            # ProductMailer.delay(run_at: 1.minutes.from_now).new_product(@product)
            flash[:notice] = "Product created successfully"
            redirect_to products_path
        else
            render :new
        end
    end

    def show
        @product = Product.find params[:id]
        @review = Review.new
        @favorite = @product.favorites.find_by_user_id current_user if user_signed_in?
    end

    def edit
    end

    def update
        if @product.update product_params
            redirect_to product_path(@product)
        else 
            render :edit
        end
    end

    def destroy
        @product.destroy
        redirect_to products_path
    end

    private

    def product_params
        params.require(:product).permit(:title, :description, :price, :tag_names)
    end
    
    def find_product
        @product = Product.find params[:id]
    end
    def authorize_user!
        redirect_to root_path, alert: 'Not Authorized' unless can?(:crud, @product)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_for @product do |f| %>
    <br>
    <div>
        <%= f.label :title %>
        <%= f.text_field :title %>
    </div>
    <div>
        <%= f.label :description %>
        <%= f.text_field :description %>
    </div>
    <div>
        <%= f.label :price %>
        <%= f.number_field :price %>
    </div>
    <div>
        <%= f.label :tag_names %>
        <%= f.text_field :tag_names %>
    </div>
    <br>
    <%= f.submit %>
<% end %>

<script>
<%# selectize doc:
https://github.com/selectize/selectize.js/blob/master/docs/usage.md
%>
$(function(){
$('#question_tag_names').selectize({
	delimeter: ',',
	persist: false,
	labelField: 'name', //Column name in db
	valueField: 'name',//Column name in db
	searchField: 'name',//Column name in db
	options: <%= Tag.select(:name).to_json(except: [:id]).html_safe %>,
	// The above line selects only names from tags table and converts them to
	// a json array of objects
	// without including ids and makes sure its a safe_html string
	// options: [{"name": "first tag"}, {"name": "second tag"}, {"name": "third tag"},
	// {"name": "fourth tag"}, {"name": "fifth tag"}, ...]
	create: function(input) {
	return {
	name: input
			}
		}
	});
});

</script> 

app/views/products/_list.html.erb
<% if @tag.present? %>
    <h2>Showing Products tagged by:
        <span class="badge badge-pill badge-primary"><%= @tag.name %></span>
    </h2>
<% end %>

<% @products.each do |product| %>
    <div>
        <h2><%= link_to product.title, product_path(product) %></h2>
        <p><%= product.description %></p>
        <p>$<%= product.price %></p>
    </div>
<% end %>

app/views/products/edit.html.erb
<%= form_for @product do |f| %>
    <br>
    <div>
        <%= f.label :title %>
        <%= f.text_field :title %>
    </div>
    <div>
        <%= f.label :description %>
        <%= f.text_field :description %>
    </div>
    <div>
        <%= f.label :price %>
        <%= f.number_field :price %>
    </div>
    <br>
    <%= f.submit %>
<% end %>

app/views/products/favorited.html.erb
<h1>Favorited Products Page</h1>

<%= render 'list' %>

app/views/products/index.html.erb
<h1>Product Index Page</h1>

<%= render 'list' %>

app/views/products/new.html.erb
<h1>New Products</h1>

<%= render 'form' %>

app/views/products/show.html.erb
<h1><%= @product.title %></h1>
<p><%= @product.description %></p>
<p>$<%= @product.price %></p>

<% unless @product.tags.empty? %>
    <p>
        Tags:
        <% @product.tags.each do |tag| %>
            <%= link_to(
                tag.name, products_path(tag: tag.name),
                class: 'badge badge-pill badge-primary'
            ) %>
        <% end %>
    </p>
<% end %>

<h4>Created by: <%= @product.user&.full_name || 'DELETED'%></h4>
<p><%= @product.created_at %></p>

<% if can?(:crud,@product)%>
<%= link_to "Edit", edit_product_path(@product)%>
<%= link_to "Delete", product_path(@product), method: :delete, data: { confirm: "Are you sure?" } %>
<% end %> 

<% if user_signed_in? && can?(:favorite, @product) %>
    <% if @favorite.present? %>
        <%= link_to 'Un Fav', favorite_path(@favorite), method: :delete %>
    <% else %>
        <%= link_to 'Fav', product_favorites_path(@product), method: :post %>
    <% end %>
<% end %>

<%= render 'reviews/form'%>

<% @product.reviews.each do |review| %>

<%= review.body %>
<%= review.rating %>
<small><%= time_ago_in_words(review.created_at)%></small>
<small> Reviewed by: <%= review.user&.full_name || 'DELETED' %></small>

<small>Liked by: <%= review.likes.count %></small>
<small>
<% if user_signed_in? && can?(:like, review) %>
<% like = current_user.likes.find_by_review_id(review) %>
    <% if like %>
        <%= link_to 'Unlike', like_path(like), method: :delete %>
        <% else %>
        <%= link_to 'Like', review_likes_path(review), method: :post %>
    <% end %>
<% end %>
</small>

<% vote = review.votes.find_by(user: current_user) %>
    <span class="vote-widget">
        <% if vote.nil? %>
          <%= link_to 'vote up', review_votes_path(review, is_up: true), method: :post %>
          <%= review.vote_total %>
          <%= link_to 'vote down', review_votes_path(review, is_up: false), method: :post %>
        <% elsif vote.is_up? %>
          <%= link_to 'vote up', vote_path(vote), method: :delete, class: 'active' %>
          <%= review.vote_total %>
          <%= link_to 'vote down', vote_path(vote, is_up: false), method: :patch %>
        <% else %>
          <%= link_to 'vote up', vote_path(vote, is_up: true), method: :patch %>
          <%= review.vote_total %>
          <%= link_to 'vote down', vote_path(vote), method: :delete %>
        <% end %>
    </span>
(Total Votes:<%= review.vote_total %>)

<% if can? :crud, review %>
<%= link_to("Delete Review", review_path(@product, review), method: :delete, data:{confirm: 'Are you sure?'})%>
<% end %>
<hr>

<% end %>