config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get('/', {to: 'home#index', as: 'root'})
  get('/about', {to: 'home#about', as: 'about'})

  get('/contacts/new', {to:'contacts#new', as: 'contacts_new'})
  post('/contacts', {to: 'contacts#create'})
  
  get('/users/panel', {to: 'users#panel', as: 'users_panel'})

  resources :products do
    resources :reviews, shallow: true, only:[:create, :destroy] do
      resources :likes, only:[:create, :destroy]
      resources :votes, only: [:create, :update, :destroy]
    end
    resources :favorites, shallow: true, only:[:create, :destroy]
  end

  resources :favorites, only: [:index]

  resources :users, only:[:new,:create]

  resource :session, only:[:new,:create, :destroy] #singlar not plural

  resources :news_articles

  # Delay_Job
  match(
    "/delayed_job",
    to: DelayedJobWeb,
    anchor:false,
    via:[:get,:post]
  )
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
      user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities

    alias_action(:create,:read,:update,:delete, to: :crud )
    
    can(:crud,Product) do |product|
      user == product.user
    end

    can(:crud,Review) do |review|
      user == review.user
    end

    can(:crud,NewsArticle) do |news_article|
      user == news_article.user
    end

    if user.is_admin?
      can :manage, :all 
    end

    can(:like, Review) do |review|
      user.persisted? && review.user != user
    end
    can(:destroy, Like) do |like|
      like.user == user
    end

    can(:favorite, Product) do |product|
      user.persisted? && product.user != user
    end
    can(:destroy, Favorite) do |favorite|
      favorite.user == user
    end

    can :vote, Review do |review|
      review.user != user 
    end 
    can :crud, Vote do |vote|
      vote.user == user 
    end 
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :product

  validates :user_id, uniqueness: { scope: :product_id }
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :review

  validates(
    :review_id,
    uniqueness: {
        scope: :user_id,
        message: "has already been liked"
    }
  )
end

app/models/news_article.rb
class NewsArticle < ApplicationRecord
    belongs_to :user
    validates :title, presence: true, uniqueness: true
    validates :description, presence: true 
    validate :published_after_create
  
    before_save :titleize_title
  
    def titleize_title
      self.title = self.title.titleize
    end
  
    def publish
      update(published_at: Time.zone.now)
    end
  
    def self.published
      where('published_at > created_at')
    end
  
    private
  
    def published_after_create
      return unless published_at.present?
      errors.add(:published_at, "published_at must be after created_at") if published_at <= created_at 
    end
end

app/models/product.rb
class Product < ApplicationRecord
    belongs_to :user
    
    has_many :reviews, dependent: :destroy

    has_many :favorites, dependent: :destroy
    has_many :favoriters, through: :favorites, source: :user

    has_many :taggings, dependent: :destroy
    has_many :tags, through: :taggings

    DEFAULT_PRICE = 1

    before_validation :set_default_price
    before_save :capitalize_title

    validates :title, presence: true, uniqueness: true
    validates :price, numericality: { greater_than: 0 }
    validates :description, presence: true, length: { minimum: 2 }

    #Getter
    def tag_names
        self.tags.map(&:name).join(", ")
    end

    #Setter
    def tag_names=(rhs)
        self.tags = rhs.strip.split(/\s*,\s*/).map do |tag_name|
        Tag.find_or_initialize_by(name: tag_name)
        end
    end

    private
    def set_default_price
        self.price ||= DEFAULT_PRICE
    end
    
    def capitalize_title
        self.title.capitalize!
    end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :product
  validates :rating, presence:{message: 'Please enter ratings.'}, numericality: {greater_than_or_equal_to: 1, lesser_than_or_equal_to: 5}

  has_many :likes, dependent: :destroy
  has_many :likers, through: :likes, source: :user

  has_many :votes, dependent: :destroy 
  has_many :voters, through: :votes, source: :user

  def vote_total 
    votes.up.count - votes.down.count 
  end 
end

app/models/tag.rb
class Tag < ApplicationRecord

    has_many :taggings, dependent: :destroy
    has_many :products, through: :taggings

    validates :name, presence: true, uniqueness: {
        case_sensitive: false
    }

    private

    def downcase_name
        self.name&.downcase!
    end
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :product
  belongs_to :tag

  validates :tag_id, uniqueness: { scope: :product_id }

end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password

    has_many :products, dependent: :nullify
    has_many :reviews, dependent: :nullify
    has_many :news_articles, dependent: :nullify
    
    has_many :likes, dependent: :destroy
    has_many :liked_reviews, through: :likes, source: :review
    
    has_many :favorites, dependent: :destroy
    has_many :favorited_products, through: :favorites, source: :product

    has_many :votes, dependent: :destroy 
    has_many :voted_reviews, through: :votes, source: :review

    def full_name
        "#{first_name} #{last_name}"
    end
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :user
  belongs_to :review

  validates :user_id, uniqueness: {
    scope: :review_id, 
    message: "has already been voted on"
  }

  validates :is_up, inclusion: {
    in: [true, false]
  }

  def self.up 
    where(is_up: true)
  end 

  def self.down 
    where(is_up: false)
  end 
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
    end
    def about
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/layouts/_alerts.html.erb
<%if flash[:notice].present? %>
<div class="alert alert-success alert-dismissible fade show" role="alert">
    <%= flash[:notice]  %> 
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
</div>
<% elsif flash[:alert].present? %> 
<div class="alert alert-danger alert-dismissible fade show" role="alert">
    <%=  flash[:alert] %> 
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
</div>

<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/">Amazing Amazon</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <%= link_to 'About', about_path, class:"nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to 'Products Page', products_path, class:"nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to 'New Product', new_product_path, class:"nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to 'Contact Us', contacts_new_path, class:"nav-link" %>
      </li>

      <% if user_signed_in? %>
      <li class="nav-item">
        <%= link_to 'Favorite Products', favorites_path %>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Hello <%= current_user.full_name %>!</a> 
      </li>
      <li class="nav-item">
        <%= link_to 'Logout', session_path, method: :delete, data:{confirm: 'Are you sure you want to log out?'},class:"nav-link" %>
      </li>
      <% else %>
      <li class="nav-item">
        <%= link_to 'Login', new_session_path, class:"nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to 'Sign Up', new_user_path, class:"nav-link" %>  
      </li>
      <% end %> 
      
      <% if current_user&.is_admin? %>
      <li class="nav-item">
        <%= link_to 'Admin Panel', users_panel_path, class:"nav-link" %>  
      </li>
      <% end %>
    </ul>
  </div>
</nav>  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Amazing Amazon</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>      
    <hr>
    <div class='container-fluid'>
      <%= render 'layouts/alerts'%>
      <%= yield %>
    </div>
  </body>
</html>